name: economy
version: '1.0-SNAPSHOT'
main: org.quintilis.economy.Economy
api-version: '1.21'

commands:
    listing:
        description: Main listing command
        aliases: [l]
        usage: /listings [subcommand]
    transfer:
        description: Main transfer command
        aliases: [t]
        usage: /transfer [subcommand]
    market:
        description: Main buy command
        aliases: [m]
        usage: /market [subcommand]